apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-page
  labels:
    app: my-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-page
  template:
    metadata:
      labels:
        app: my-page 
    spec:
      containers:
      - name: my-page
        image: abc5482/my-page:latest
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
    nodePort: 31110